#include "X32Utils.h"

const char *inputMap[65] = {
    "",
    "In01",
    "In02",
    "In03",
    "In04",
    "In05",
    "In06",
    "In07",
    "In08",
    "In09",
    "In10",
    "In11",
    "In12",
    "In13",
    "In14",
    "In15",
    "In16",
    "In17",
    "In18",
    "In19",
    "In20",
    "In21",
    "In22",
    "In23",
    "In24",
    "In25",
    "In26",
    "In27",
    "In28",
    "In29",
    "In30",
    "In31",
    "In32",
    "Aux1",
    "Aux2",
    "Aux3",
    "Aux4",
    "Aux5",
    "Aux6",
    "USB L",
    "USB R",
    "Fx 1L",
    "Fx 1R",
    "Fx 2L",
    "Fx 2R",
    "Fx 3L",
    "Fx 3R",
    "Fx 4L",
    "Fx 4R",
    "Bus 01",
    "Bus 02",
    "Bus 03",
    "Bus 04",
    "Bus 05",
    "Bus 06",
    "Bus 07",
    "Bus 08",
    "Bus 09",
    "Bus 10",
    "Bus 11",
    "Bus 12",
    "Bus 13",
    "Bus 14",
    "Bus 15",
    "Bus 16",
};

ChFaderBank channelBanks[4] = {
    {CH_1_8, {
                 "/ch/01",
                 "/ch/02",
                 "/ch/03",
                 "/ch/04",
                 "/ch/05",
                 "/ch/06",
                 "/ch/07",
                 "/ch/08",
             }},
    {CH_9_16, {
                  "/ch/09",
                  "/ch/10",
                  "/ch/11",
                  "/ch/12",
                  "/ch/13",
                  "/ch/14",
                  "/ch/15",
                  "/ch/16",
              }},
    {CH_17_24, {
                   "/ch/17",
                   "/ch/18",
                   "/ch/19",
                   "/ch/20",
                   "/ch/21",
                   "/ch/22",
                   "/ch/23",
                   "/ch/24",
               }},
    {CH_25_32, {
                   "/ch/25",
                   "/ch/26",
                   "/ch/27",
                   "/ch/28",
                   "/ch/29",
                   "/ch/30",
                   "/ch/31",
                   "/ch/32",
               }},
};

GrpFaderBank groupBanks[5] = {
    {DCA_1_8, {
                  "/dca/1",
                  "/dca/2",
                  "/dca/3",
                  "/dca/4",
                  "/dca/5",
                  "/dca/6",
                  "/dca/7",
                  "/dca/8",
              }},
    {BUS_1_8, {
                  "/bus/01",
                  "/bus/02",
                  "/bus/03",
                  "/bus/04",
                  "/bus/05",
                  "/bus/06",
                  "/bus/07",
                  "/bus/08",
              }},
    {BUS_9_16, {
                   "/bus/09",
                   "/bus/10",
                   "/bus/11",
                   "/bus/12",
                   "/bus/13",
                   "/bus/14",
                   "/bus/15",
                   "/bus/16",
               }},
    {MATRIX_MAIN_C, {
                        "/mtx/01",
                        "/mtx/02",
                        "/mtx/03",
                        "/mtx/04",
                        "/mtx/05",
                        "/mtx/06",
                        "",
                        "/main/m",
                    }},
    {CH_1_16_SPREAD, {
                         "/ch/09",
                         "/ch/10",
                         "/ch/11",
                         "/ch/12",
                         "/ch/13",
                         "/ch/14",
                         "/ch/15",
                         "/ch/16",
                     }},

};

const ChannelInfo X32Channels[80] = {
    // Channels config
    {"/ch/01", true},
    {"/ch/02", true},
    {"/ch/03", true},
    {"/ch/04", true},
    {"/ch/05", true},
    {"/ch/06", true},
    {"/ch/07", true},
    {"/ch/08", true},
    {"/ch/09", true},
    {"/ch/10", true},
    {"/ch/11", true},
    {"/ch/12", true},
    {"/ch/13", true},
    {"/ch/14", true},
    {"/ch/15", true},
    {"/ch/16", true},
    {"/ch/17", true},
    {"/ch/18", true},
    {"/ch/19", true},
    {"/ch/20", true},
    {"/ch/21", true},
    {"/ch/22", true},
    {"/ch/23", true},
    {"/ch/24", true},
    {"/ch/25", true},
    {"/ch/26", true},
    {"/ch/27", true},
    {"/ch/28", true},
    {"/ch/29", true},
    {"/ch/30", true},
    {"/ch/31", true},
    {"/ch/32", true},
    // Aux in config
    {"/auxin/01", true},
    {"/auxin/02", true},
    {"/auxin/03", true},
    {"/auxin/04", true},
    {"/auxin/05", true},
    {"/auxin/06", true},
    {"/auxin/07", true},
    {"/auxin/08", true},
    // FX returns
    {"/fxrtn/01", false},
    {"/fxrtn/02", false},
    {"/fxrtn/03", false},
    {"/fxrtn/04", false},
    {"/fxrtn/05", false},
    {"/fxrtn/06", false},
    {"/fxrtn/07", false},
    {"/fxrtn/08", false},
    // Busses
    {"/bus/01", false},
    {"/bus/02", false},
    {"/bus/03", false},
    {"/bus/04", false},
    {"/bus/05", false},
    {"/bus/06", false},
    {"/bus/07", false},
    {"/bus/08", false},
    {"/bus/09", false},
    {"/bus/10", false},
    {"/bus/11", false},
    {"/bus/12", false},
    {"/bus/13", false},
    {"/bus/14", false},
    {"/bus/15", false},
    {"/bus/16", false},
    // Matrix
    {"/mtx/01", false},
    {"/mtx/02", false},
    {"/mtx/03", false},
    {"/mtx/04", false},
    {"/mtx/05", false},
    {"/mtx/06", false},
    // Main Stereo-Mono
    {"/main/st", false},
    {"/main/m", false},
    // DCAs
    {"/dca/1", false},
    {"/dca/2", false},
    {"/dca/3", false},
    {"/dca/4", false},
    {"/dca/5", false},
    {"/dca/6", false},
    {"/dca/7", false},
    {"/dca/8", false},
};